"""empty message

Revision ID: 910bc86f87ad
Revises: 
Create Date: 2018-11-16 13:01:48.004183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910bc86f87ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classify',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=64), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('sub_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_index(op.f('ix_classify_c_name'), 'classify', ['c_name'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('news',
    sa.Column('new_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('news_date', sa.String(length=64), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_hot', sa.Integer(), nullable=True),
    sa.Column('classify_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classify_id'], ['classify.c_id'], ),
    sa.PrimaryKeyConstraint('new_id')
    )
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    op.create_table('subscription',
    sa.Column('sub_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_sub', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['classify.c_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sub_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_classify_c_name'), table_name='classify')
    op.drop_table('classify')
    # ### end Alembic commands ###
